<?php
class xudfSetting extends ActiveRecord {
    const PLUGIN_CLASS_NAME = ilUdfEditorPlugin::class;
    const DB_TABLE_NAME = 'xudf_setting';

    const REDIRECT_STAY_IN_FORM = 'stay_in_form';
    const REDIRECT_TO_ILIAS_OBJECT = 'to_ilias_object';
    const REDIRECT_TO_URL = 'to_url';

    public function getConnectorContainerName(): string
    {
        return self::DB_TABLE_NAME;
    }

    /**
     * @var int
     *
     * @con_has_field    true
     * @con_fieldtype    integer
     * @con_length       8
     * @con_is_notnull   true
     * @con_is_primary   true
     */
    protected $obj_id;
    /**
     * @var bool
     *
     * @con_has_field    true
     * @con_fieldtype    integer
     * @con_length       1
     * @con_is_notnull   true
     */
    protected $is_online = false;
    /**
     * @var bool
     *
     * @con_has_field    true
     * @con_fieldtype    integer
     * @con_length       1
     * @con_is_notnull   true
     */
    protected $show_info_tab = false;
    /**
     * @var bool
     *
     * @con_has_field    true
     * @con_fieldtype    integer
     * @con_length       1
     * @con_is_notnull   true
     */
    protected $mail_notification = false;
	/**
	 * @var string
	 *
	 * @con_has_field    true
	 * @con_fieldtype    text
	 * @con_length       256
	 */
    protected $additional_notification = '';
    /**
     * @var string
     *
     * @con_has_field    true
     * @con_fieldtype    text
     * @con_length       64
     */
    protected $redirect_type = self::REDIRECT_STAY_IN_FORM;
    /**
     * @var string
     *
     * @con_has_field    true
     * @con_fieldtype    text
     * @con_length       256
     */
    protected $redirect_value;
    /**
     * @var string
     *
     * @con_has_field    true
     * @con_fieldtype    text
     * @con_is_notnull   true
     */
    protected $notification_name = "";


    /**
     * @return int
     */
    public function getObjId(): int
    {
        return $this->obj_id;
    }

    /**
     * @param int $obj_id
     */
    public function setObjId($obj_id): void
    {
        $this->obj_id = $obj_id;
    }

    /**
     * @return bool
     */
    public function isOnline(): bool
    {
        return $this->is_online;
    }

    /**
     * @param bool $is_online
     */
    public function setIsOnline($is_online): void
    {
        $this->is_online = $is_online;
    }

    /**
     * @return bool
     */
    public function isShowInfoTab(): bool
    {
        return $this->show_info_tab;
    }

    /**
     * @param bool $show_info_tab
     */
    public function setShowInfoTab($show_info_tab): void
    {
        $this->show_info_tab = $show_info_tab;
    }

    /**
     * @return bool
     */
    public function hasMailNotification(): bool
    {
        return $this->mail_notification;
    }

    /**
     * @param bool $mail_notification
     */
    public function setMailNotification($mail_notification): void
    {
        $this->mail_notification = $mail_notification;
    }

	/**
	 * @return string
	 */
	public function getAdditionalNotification(): string
    {
		return $this->additional_notification;
	}

	/**
	 * @param string $additional_notification
	 */
	public function setAdditionalNotification($additional_notification): void
    {
		$this->additional_notification = $additional_notification;
	}


    /**
     * @return string
     */
    public function getRedirectType() : string
    {
        return $this->redirect_type ?: self::REDIRECT_STAY_IN_FORM;
    }


    /**
     * @param string $redirect_type
     */
    public function setRedirectType(string $redirect_type): void
    {
        $this->redirect_type = $redirect_type;
    }


    /**
     * @return string
     */
    public function getRedirectValue() : string
    {
        return $this->redirect_value;
    }


    /**
     * @param string $redirect_value
     */
    public function setRedirectValue(string $redirect_value): void
    {
        $this->redirect_value = $redirect_value;
    }

    /**
     * @param $primary_key
     * @param array $add_constructor_args
     * @return self
     */
    public static function find($primary_key, array $add_constructor_args = array()): xudfSetting
    {
        return parent::find($primary_key, $add_constructor_args); // TODO: Change the autogenerated stub
    }


    /**
     * @return NotificationInterface
     */
    public function getNotification() : NotificationInterface
    {
        if (empty($this->notification_name)) {
            $this->notification_name = "object_" . $this->getObjId();

            $this->store();
        }

        $notification = self::notifications4plugin()->notifications()->getNotificationByName($this->notification_name);

        if ($notification === null) {
            $notification = self::notifications4plugin()->notifications()->factory()->newInstance();

            //todo
            //$notification->setTitle(self::plugin()->translate("notification"));

            $notification->setTitle("TODO");

            $notification->setName($this->notification_name);

            $notification->setSubject("ILIAS: {{ object.getTitle }}", "default");

            $notification->setText("Sehr geehrte/r {{ user.getFullname }},

Sie haben im Objekt „{{ object.getTitle }}“ die folgenden Angaben ausgewählt:

{% for key, value in user_defined_data %}
{{ key }} : {{ value }}

{% endfor %}
{{ \"now\"|date('d.m.Y H:i') }}", "default");

            self::notifications4plugin()->notifications()->storeNotification($notification);
        }

        return $notification;
    }
}